"""Fortran90 export for committed metabolic models."""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path
import re

from metabolang.model import Gate, Relation, build_odes


PARAMETER_ALIASES = {
    "k": "K",
    "k1": "K1",
    "k2": "K2",
    "V": "V",
    "K": "KM",
    "n": "N",
    "a": "A",
}


def export_fortran_model(
    species: list[str],
    relations: list[Relation],
    output_dir: Path,
    stem: str = "generated_model",
) -> tuple[Path, Path]:
    """Write a Fortran subroutine and editable parameter file."""

    output_dir.mkdir(parents=True, exist_ok=True)
    parameter_records, named_relations = _name_parameters(relations)
    state_names = _unique_identifiers(species, prefix="S")

    parameter_path = output_dir / f"{stem}_parameters"
    fortran_path = output_dir / f"{stem}.f90"

    parameter_path.write_text(_render_parameter_file(parameter_records), encoding="utf-8")
    fortran_path.write_text(
        _render_fortran(species, state_names, parameter_records, named_relations),
        encoding="utf-8",
    )
    return fortran_path, parameter_path


def _name_parameters(relations: list[Relation]) -> tuple[list[tuple[str, str]], list[Relation]]:
    records: list[tuple[str, str]] = []
    named_relations = []

    for relation_index, relation in enumerate(relations, start=1):
        params = {}
        for raw_name, value in relation.params.items():
            name = _parameter_name(raw_name, relation_index)
            params[raw_name] = name
            records.append((name, value))

        gates = []
        for gate_index, gate in enumerate(relation.gates, start=1):
            gate_params = {}
            for raw_name, value in gate.params.items():
                name = _parameter_name(raw_name, relation_index, gate_index)
                gate_params[raw_name] = name
                records.append((name, value))
            gates.append(replace(gate, params=gate_params))

        named_relations.append(replace(relation, params=params, gates=gates))

    return records, named_relations


def _parameter_name(raw_name: str, relation_index: int, gate_index: int | None = None) -> str:
    base = PARAMETER_ALIASES.get(raw_name, _sanitize_identifier(raw_name, "P").upper())
    suffix = f"R{relation_index:02d}"
    if gate_index is not None:
        suffix = f"{suffix}_G{gate_index:02d}"
    return f"{base}_{suffix}"


def _render_parameter_file(records: list[tuple[str, str]]) -> str:
    lines = ["# parameters generated by the metabolic interpreter", ""]
    for name, value in records:
        lines.append(f"{name} = {value}")
    lines.append("")
    return "\n".join(lines)


def _render_fortran(
    species: list[str],
    state_names: list[str],
    parameter_records: list[tuple[str, str]],
    relations: list[Relation],
) -> str:
    odes = build_odes(species, relations)
    parameter_names = [name for name, _value in parameter_records]
    declarations = _wrap_declaration("      real*8 :: ", state_names)
    parameter_declarations = _wrap_declaration("      real*8 :: ", parameter_names)

    lines = [
        "      subroutine computeRates(time,CONSTS,RATES,STATES,k)",
        "!===========================================================",
        "! GENERATED METABOLIC MODEL",
        "!===========================================================",
        "      implicit none",
        "      real*8 :: STATES(*), RATES(*), CONSTS(*)",
        "      real*4 :: time",
        "      real*8 :: k",
        "",
        "!------------------------",
        "! STATE VARIABLES",
        "!------------------------",
    ]
    for index, (species_name, state_name) in enumerate(zip(species, state_names), start=1):
        lines.append(f"! STATES({index}) is {species_name}")
    lines.extend(["", declarations])

    if parameter_names:
        lines.extend(
            [
                "",
                "!------------------------",
                "! PARAMETERS",
                "!------------------------",
                parameter_declarations,
            ]
        )

    lines.extend(
        [
            "",
            "!------------------------",
            "! UNPACK STATE",
            "!------------------------",
        ]
    )
    for index, state_name in enumerate(state_names, start=1):
        lines.append(f"      {state_name} = STATES({index})")

    if parameter_names:
        lines.extend(
            [
                "",
                "!------------------------",
                "! MODEL PARAMETERS",
                "!------------------------",
            ]
        )
        for index, name in enumerate(parameter_names, start=1):
            lines.append(f"      {name} = CONSTS({index})")

    lines.extend(
        [
            "",
            "!------------------------",
            "! ODE SYSTEM",
            "!------------------------",
        ]
    )
    species_to_state = dict(zip(species, state_names))
    for index, species_name in enumerate(species, start=1):
        expression = _fortran_expression(odes[species_name], species_to_state)
        lines.extend(_assignment_lines(f"      RATES({index}) = ", expression))

    lines.extend(
        [
            "      return",
            "      end subroutine computeRates",
            "",
        ]
    )
    return "\n".join(lines)


def _fortran_expression(expression: str, species_to_state: dict[str, str]) -> str:
    converted = expression.replace("^", "**")
    for species_name in sorted(species_to_state, key=len, reverse=True):
        converted = re.sub(
            rf"\b{re.escape(species_name)}\b",
            species_to_state[species_name],
            converted,
        )
    return converted


def _assignment_lines(prefix: str, expression: str, width: int = 76) -> list[str]:
    if len(prefix) + len(expression) <= width:
        return [f"{prefix}{expression}"]

    pieces = re.split(r"(\s[+-]\s)", expression)
    lines = []
    current = prefix
    for piece in pieces:
        if not piece:
            continue
        if len(current) + len(piece) > width and current.strip() != prefix.strip():
            lines.append(current.rstrip() + " &")
            current = "                " + piece.lstrip()
        else:
            current += piece
    lines.append(current.rstrip())
    return lines


def _wrap_declaration(prefix: str, names: list[str], width: int = 76) -> str:
    if not names:
        return f"{prefix}DUMMY"

    lines = []
    current = prefix
    for index, name in enumerate(names):
        piece = name if index == 0 else f", {name}"
        if len(current) + len(piece) > width:
            lines.append(current.rstrip() + " &")
            current = "     &     " + name
        else:
            current += piece
    lines.append(current)
    return "\n".join(lines)


def _unique_identifiers(names: list[str], prefix: str) -> list[str]:
    used = set()
    identifiers = []
    for name in names:
        identifier = _sanitize_identifier(name, prefix).upper()
        base = identifier
        counter = 2
        while identifier in used:
            identifier = f"{base}_{counter}"
            counter += 1
        used.add(identifier)
        identifiers.append(identifier)
    return identifiers


def _sanitize_identifier(name: str, prefix: str) -> str:
    identifier = re.sub(r"[^A-Za-z0-9_]", "_", name.strip())
    if not identifier or not identifier[0].isalpha():
        identifier = f"{prefix}_{identifier}"
    return identifier
